{% set name = "tobac" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/climate-processes/{{name}}/archive/v{{version}}.tar.gz
  sha256: f443c86d3d41ac55fdac71e9f2080ba4cdb1583ee632d768c7484d513399c40f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - pandas
    - pytables
    - matplotlib 
    - iris 
    - xarray 
    - cf_units
    - cartopy
    - trackpy

test:
  imports:
    - tobac
    - tobac.testing
  source_files:
    - tobac/tests/test_import.py
    - tobac/tests/test_sample_data.py
  requires:
    - pytest
  commands:
    - pytest tobac/tests
about:
  home: http://github.com/simplejson/simplejson
  license:  BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Tracking and Object-Based Analysis of Clouds'

  description:  tobac is a flexible frameork for cloud tracking of different types of datasets
  doc_url: http://tobac.readthedocs.io/
  dev_url: https://github.com/climate-processes/tobac

extra:
  recipe-maintainers:
    - mheikenfeld
    - w-k-jones
