{% set name = "tobac" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tobac-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 967f86137b57afabf828e17b36ea8a66e834c352894a33e808e219bb9fcdde72

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - pandas
    - matplotlib-base
    - iris
    - xarray
    - cartopy
    - trackpy
    - typing_extensions

test:
  imports:
    - tobac
    - tobac.testing
  source_files:
    - tobac/tests/test_import.py
    - tobac/tests/test_sample_data.py
    - tobac/tests/test_feature_detection.py
    - tobac/tests/test_segmentation.py
    - tobac/tests/test_tracking.py
    - tobac/tests/test_merge_split.py
    - tobac/tests/test_testing.py
    - tobac/tests/test_utils.py
  requires:
    - pytest
  commands:
    - pytest tobac/tests
about:
  home: https://github.com/tobac-project/tobac
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tracking and Object-Based Analysis of Clouds

  description: tobac is a flexible frameork for cloud tracking of different types of datasets
  doc_url: http://tobac.readthedocs.io/
  dev_url: https://github.com/tobac-project/tobac

extra:
  recipe-maintainers:
    - JuliaKukulies
    - freemansw1
    - mheikenfeld
    - w-k-jones
