{% set name = "tobac" %}
{% set version = "1.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tobac-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9f46d0a898af6310a82d14fb9d0250a8d24ae3457266523f60a6ebca834c50a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - pandas
    - matplotlib-base
    - iris
    - xarray
    - cartopy
    - trackpy
    - typing_extensions

test:
  imports:
    - tobac
    - tobac.testing
  source_files:
    - tobac/tests/test_import.py
    - tobac/tests/test_sample_data.py
    - tobac/tests/test_feature_detection.py
    - tobac/tests/segmentation_tests/test_segmentation.py
    - tobac/tests/test_tracking.py
    - tobac/tests/test_merge_split.py
    - tobac/tests/test_testing.py
    - tobac/tests/test_utils.py
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    - pytest tobac/tests
about:
  home: https://github.com/tobac-project/tobac
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tracking and Object-Based Analysis of Clouds

  description: tobac is a flexible frameork for cloud tracking of different types of datasets
  doc_url: http://tobac.readthedocs.io/
  dev_url: https://github.com/tobac-project/tobac

extra:
  recipe-maintainers:
    - JuliaKukulies
    - freemansw1
    - mheikenfeld
    - w-k-jones
